spring:
  profiles:
    active: dev
  ktor:
    port: 8080
  data:
    mongodb:
      uri: mongodb://localhost/tg
      auto-index-creation: true
  task:
    scheduling:
      pool:
        size: 10
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.office365.com
    username: x@x.com
    password: 0
    properties:
      mail:
        from: x@x.com
        smtp:
          starttls:
            enable: true
logging:
  file:
    path: ./tmp

kuku:
  telegram:
    token:
    creatorId: 0
    proxyHost:
    proxyPort: 0
    proxyType: direct
    url:
    localPath:
    api:
