spring:
  profiles:
    active: dev
  ktor:
    port: 8080
  data:
    mongodb:
      uri: mongodb://localhost/tg
      auto-index-creation: true
  task:
    scheduling:
      pool:
        size: 10
  threads:
    virtual:
      enabled: true
logging:
  file:
    path: ./tmp

kuku:
  telegram:
    token:
    creatorId: 0
    proxyHost:
    proxyPort: 0
    proxyType: direct
    url:
    localPath:
    api:
